name: Déclencheur de mise à jour manuelle

on:
  workflow_dispatch:
    inputs:
      GRAND_LYON_USERNAME:
        description: 'Username for Grand Lyon data download'
        required: true
      GRAND_LYON_PASSWORD:
        description: 'Password for Grand Lyon data download'
        required: true
        
permissions:
  contents: write
  packages: write

jobs:
  call-update:
    uses: ./.github/workflows/france_services_locaux.yaml
    secrets:
      GRAND_LYON_USERNAME: ${{ inputs.GRAND_LYON_USERNAME }}
      GRAND_LYON_PASSWORD: ${{ inputs.GRAND_LYON_PASSWORD }}
