name: Manual Update Trigger Trenitalia Netex -> GTFS

on:
  workflow_dispatch:
    
permissions:
  contents: write
  packages: write

jobs:
  call-update:
    uses: ./.github/workflows/trenitalia.yml
