name: Download SE gtfs schedule

on:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write
  packages: write

jobs:
  call-update:
    uses: ./.github/workflows/trafiklab_gtfs_clone.yml
