name: Trafiklab download

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Se GTFS
        run: wget  --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" https://opendata.samtrafiken.se/gtfs-sweden/sweden.zip?key=52ee277737404739b8996e022eb09c2c -O sweden.zip

      - name: Upload Asset Se GTFS
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: sweden.zip # Replace with the actual path to your file
          ASSET_NAME: sweden.zip     # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''
