name: Generate Trenitalia GTFS

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-trenitalia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip gh curl wget

      - name: Download TrenItalia Netex file
        run: |
          wget -O trenitalia.xml.gz "https://www.cciss.it/nap/mmtis/public/api/v1/download/blob/Asset/1080596/resource"
          gunzip -k trenitalia.xml.gz

      - name: Upload raw trenitalia
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload latest trenitalia.xml.gz --repo catenarytransit/pfaedled-gtfs-actions --clobber

      - name: Zip TrenItalia Netex file
        run: |
          zip trenitalia.zip trenitalia.xml

      - name: Build netex-to-gtfs-converter
        run: |
          git clone https://github.com/catenarytransit/netex-to-gtfs-converter
          cd netex-to-gtfs-converter
          cargo build --release

      - name: Convert to GTFS
        run: |
          ./netex-to-gtfs-converter/target/release/netex-to-gtfs-converter --input trenitalia.xml --output trenitalia_gtfs_out/

      - name: Zip folder
        run: zip -r trenitalia_gtfs.zip trenitalia_gtfs_out/

      - name: Upload to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload latest trenitalia_gtfs.zip --repo catenarytransit/pfaedled-gtfs-actions --clobber
