name: Generate Trenitalia GTFS

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-trenitalia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip gh curl wget

      - name: Download TrenItalia Netex file
        run: |
          wget -O trenitalia.xml.gz "https://www.cciss.it/nap/mmtis/public/api/v1/download/blob/Asset/1080596/resource"
          gunzip trenitalia.xml.gz

      - name: Zip TrenItalia Netex file
        run: |
          zip trenitalia.zip trenitalia.xml

      - name: Build trenitalia-converter
        run: |
          cd trenitalia-converter
          mvn -B clean package

      - name: Convert to GTFS
        run: |
          java -jar trenitalia-converter/target/trenitalia-converter-1.0-SNAPSHOT-jar-with-dependencies.jar trenitalia.zip trenitalia_gtfs.zip

      - name: Upload to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload latest trenitalia_gtfs.zip --repo catenarytransit/pfaedled-gtfs-actions --clobber
