name: Update Pfaedle files

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download unzip and zip
        run: sudo apt install unzip zip

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: Build Pfaedle
        run: |
          git clone --recurse-submodules https://github.com/ad-freiburg/pfaedle
          cd pfaedle
          mkdir build && cd build
          cmake ..
          make -j
          sudo make install
          cd ..

      - name: Current dir
        run: |
          echo "current dir"
          echo $(pwd)
          echo "ls"
          ls

      - name: Download osm files
        run: |
          wget https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf
          wget https://download.geofabrik.de/north-america/us/california/socal-latest.osm.pbf
          wget https://download.geofabrik.de/europe/portugal-latest.osm.pbf
          wget https://github.com/catenarytransit/osm-filter/releases/download/latest/railonly-europe-latest.osm.pbf
          wget https://download.geofabrik.de/europe/switzerland-latest.osm.pbf

      - name: Filter Portugal
        run: |
          osmium tags-filter -o railonly-portugal-latest.osm.pbf --expressions=railway-filter.txt portugal-latest.osm.pbf
          
      - name: Filter Socal rail entwork
        run: |
          osmium tags-filter -o railonly-socal-latest.osm.pbf --expressions=railway-filter.txt socal-latest.osm.pbf

      - name: Convert OSM files
        run: |
          osmconvert railonly-socal-latest.osm.pbf -o=railonly-socal-latest.osm
          osmconvert ile-de-france-latest.osm.pbf -o=ile-de-france-latest.osm
          osmconvert railonly-portugal-latest.osm.pbf -o=railonly-portugal-latest.osm
          osmconvert railonly-europe-latest.osm.pbf -o=railonly-europe-latest.osm
          osmconvert switzerland-latest.osm.pbf -o=switzerland-latest.osm

      - name: Download zip of ile de france gtfs
        uses: wei/wget@v1
        with:
          args: https://eu.ftp.opendatasoft.com/stif/GTFS/IDFM-gtfs.zip

      - name: Download SNCF files
        run: |
          wget https://eu.ftp.opendatasoft.com/sncf/plandata/export_gtfs_voyages.zip
          wget https://eu.ftp.opendatasoft.com/sncf/plandata/export-intercites-gtfs-last.zip
          wget https://eu.ftp.opendatasoft.com/sncf/plandata/export-ter-gtfs-last.zip

      - name: Extract SNCF
        run: |
          unzip export_gtfs_voyages.zip -d export_gtfs_voyages
          unzip export-intercites-gtfs-last.zip -d sncf_intercites 
          unzip export-ter-gtfs-last.zip -d sncf_ter

      - name: Run pfaedle SNCF voyages
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm export_gtfs_voyages  -F --inplace

      - name: Run pfaedle SNCF intercites
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm sncf_intercites  -F --inplace

      - name: Run pfaedle SNCF TER
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm sncf_ter -F --inplace

      - name: Zip pfaedle SNCF Voyages
        run: zip -r export_gtfs_voyages_pfaedle.zip export_gtfs_voyages

      - name: Zip pfaedle SNCF intercites
        run: zip -r sncf_intercites_pfaedle.zip sncf_intercites

      - name: Zip pfaedle SNCF TER
        run: zip -r sncf_ter_pfaedle.zip sncf_ter

      - name: Upload SNCF Voyages results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: export_gtfs_voyages_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: export_gtfs_voyages_pfaedle.zip # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Upload SNCF TER results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: sncf_ter_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: sncf_ter_pfaedle.zip # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Upload SNCF intercites results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: sncf_intercites_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: sncf_intercites_pfaedle.zip # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Download SNCB GTFS
        run: wget https://sncb-opendata.hafas.de/gtfs/static/c21ac6758dd25af84cca5b707f3cb3de -O sncb_gtfs.zip

      - name: Download metrolink gtfs
        run: wget https://metrolinktrains.com/globalassets/about/gtfs/gtfs.zip -O metrolink.zip

      - name: Download PC GTFS
        run: wget https://publico.cp.pt/gtfs/gtfs.zip -O pc_gtfs.zip

      - name: Download Renfe Operadora
        run: wget https://ssl.renfe.com/gtransit/Fichero_AV_LD/google_transit.zip -O renfe_operadora.zip

      - name: Unzip PC GTFS
        run: unzip pc_gtfs.zip -d pc_gtfs

      - name: SNCB GTFS
        run: unzip sncb_gtfs.zip -d sncb_gtfs

      - name: Unzip renfe operadora
        run: unzip renfe_operadora.zip -d renfe_operadora

      - name: Run pfaedle Portugal
        run: ./pfaedle/build/pfaedle -x railonly-portugal-latest.osm pc_gtfs -F --inplace

      - name: Zip PC results
        run: zip -r pc_gtfs_pfaedle.zip pc_gtfs

      - name: Upload PC results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: pc_gtfs_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: pc_gtfs_pfaedle.zip      # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''
      
      - name: Run pfaedle SNCB
        run: ./pfaedle/build/pfaedle -x railonly-portugal-latest.osm sncb_gtfs -F --inplace

      - name: Zip SNCF pfaedle result
        run: zip -r sncb_gtfs_pfaedle.zip sncb_gtfs

      - name: Upload SNCB result
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: sncb_gtfs_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: sncb_gtfs_pfaedle.zip # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''     

      - name: Run pfaedle renfe operadora
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm renfe_operadora -F --inplace

      - name: Zip renfe operadora results
        run: zip -r renfe_operadora_pfaedle.zip renfe_operadora

      - name: Upload Renfe Operadora
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: renfe_operadora_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: renfe_operadora_pfaedle.zip # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''        

      - name: Unzip Metrolink GTFS
        run: |
          mkdir metrolink-gtfs  
          unzip metrolink.zip -d metrolink-gtfs  

      - name: Unzip of ile de france gtfs
        run: |
          mkdir IDFM-gtfs
          unzip IDFM-gtfs.zip -d IDFM-gtfs

      - name: Run Metrolink pfaedle
        run: |
          ./pfaedle/build/pfaedle -x railonly-socal-latest.osm metrolink-gtfs -F --inplace

      - name: Zip metrolink file
        run: zip -r metrolink-pfaedle.zip metrolink-gtfs
        
      - name: Run Ile de france pfaedle Local rail and bus
        run: |
          ./pfaedle/build/pfaedle -x ile-de-france-latest.osm IDFM-gtfs -F --inplace --mots metro,streetcar,tram,subway,coach,monorail,trolley,trolleybus,bus

      - name: Run Ile de france pfaedle Intercity rail
        run: |
          ./pfaedle/build/pfaedle -x railonly-europe-latest.osm IDFM-gtfs -F --inplace --mots rail

      - name: Zip the resulting GTFS Ile de France
        run: zip -r IDFM-gtfs-pfaedle.zip IDFM-gtfs

      - name: Upload Metrolink Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: metrolink-pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: metrolink-pfaedle.zip     # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Upload Asset Ile De France
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: IDFM-gtfs-pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: IDFM-gtfs-pfaedle.zip      # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Download Swiss GTFS
        run: wget https://data.opentransportdata.swiss/en/dataset/timetable-2025-gtfs2020/permalink -O swiss_gtfs.zip

      - name: Unzip Swiss GTFS
        run: unzip swiss_gtfs.zip -d swiss_gtfs

      - name: Run Pfaedle Swiss Bus network
        run: ./pfaedle/build/pfaedle -x switzerland-latest.osm swiss_gtfs -F --inplace --mots bus,trolley-bus,trolleybus,trolley

      - name: Run Pfaedle Swiss Rail network
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm swiss_gtfs -F --inplace --mots rail,metro,subway,tram,streetcar

      - name: Zip swiss gtfs
        run:  zip -r swiss_gtfs_pfaedle.zip swiss_gtfs

      - name: Upload Asset Swiss GTFS
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: swiss_gtfs_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: swiss_gtfs_pfaedle.zip     # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''
