name: Update Pfaedle files

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download unzip and zip
        run: sudo apt install unzip zip

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: Build Pfaedle
        run: |
          git clone --recurse-submodules https://github.com/ad-freiburg/pfaedle
          cd pfaedle
          mkdir build && cd build
          cmake ..
          make -j
          sudo make install
          cd ..

      - name: Current dir
        run: |
          echo "current dir"
          echo $(pwd)
          echo "ls"
          ls

      - name: Download osm files
        run: |
          wget https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf
          wget https://download.geofabrik.de/asia/china/guangdong-latest.osm.pbf
          wget https://download.geofabrik.de/north-america/us/california/socal-latest.osm.pbf
          wget https://download.geofabrik.de/europe/portugal-latest.osm.pbf
          wget https://github.com/catenarytransit/osm-filter/releases/download/latest/railonly-europe-latest.osm.pbf

      - name: Filter Portugal
        run: |
          osmium tags-filter -o railonly-portugal-latest.osm.pbf --expressions=railway-filter.txt portugal-latest.osm.pbf
          
      - name: Filter Socal rail entwork
        run: |
          osmium tags-filter -o railonly-socal-latest.osm.pbf --expressions=railway-filter.txt socal-latest.osm.pbf

      - name: Convert OSM files
        run: |
          osmconvert railonly-socal-latest.osm.pbf -o=railonly-socal-latest.osm
          osmconvert ile-de-france-latest.osm.pbf -o=ile-de-france-latest.osm
          osmconvert guangdong-latest.osm.pbf -o=guangdong-latest.osm
          osmconvert railonly-portugal-latest.osm.pbf -o=railonly-portugal-latest.osm
          osmconvert railonly-europe-latest.osm.pbf -o=railonly-europe-latest.osm

      - name: Download zip of ile de france gtfs
        run: wget https://eu.ftp.opendatasoft.com/stif/GTFS/IDFM-gtfs.zip

      - name: Download SNCF files
        run: |
          wget https://eu.ftp.opendatasoft.com/sncf/plandata/export_gtfs_voyages.zip
          wget https://eu.ftp.opendatasoft.com/sncf/plandata/export-intercites-gtfs-last.zip
          wget https://eu.ftp.opendatasoft.com/sncf/plandata/export-ter-gtfs-last.zip

      - name: Extract SNCF
        run: |
          unzip export_gtfs_voyages.zip -d export_gtfs_voyages
          unzip export-intercites-gtfs-last.zip -d sncf_intercites 
          unzip export-ter-gtfs-last.zip -d sncf_ter

      - name: Run pfaedle SNCF voyages
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm export_gtfs_voyages -o export_gtfs_voyages_pfaedle

      - name: Run pfaedle SNCF intercites
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm sncf_intercites -o sncf_intercites_pfaedle

      - name: Run pfaedle SNCF TER
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm sncf_ter -o sncf_ter_pfaedle

      - name: Zip pfaedle SNCF Voyages
        run: zip -r export_gtfs_voyages_pfaedle.zip export_gtfs_voyages_pfaedle

      - name: Zip pfaedle SNCF intercites
        run: zip -r sncf_intercites_pfaedle.zip sncf_intercites_pfaedle

      - name: Zip pfaedle SNCF TER
        run: zip -r sncf_ter_pfaedle.zip sncf_ter_pfaedle

      - name: Upload SNCF Voyages results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: export_gtfs_voyages_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: export_gtfs_voyages_pfaedle.zip # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Upload SNCF TER results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: sncf_ter_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: sncf_ter_pfaedle.zip # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Upload SNCF intercites results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: sncf_intercites_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: sncf_intercites_pfaedle.zip # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Download Hong Kong GTFS
        run: wget https://static.data.gov.hk/td/pt-headway-tc/gtfs.zip -O hk_gtfs.zip

      - name: Download metrolink gtfs
        run: wget https://metrolinktrains.com/globalassets/about/gtfs/gtfs.zip -O metrolink.zip

      - name: Download PC GTFS
        run: wget https://publico.cp.pt/gtfs/gtfs.zip -O pc_gtfs.zip

      - name: Unzip PC GTFS
        run: unzip pc_gtfs.zip -d pc_gtfs

      - name: Run pfaedle Portugal
        run: ./pfaedle/build/pfaedle -x railonly-portugal-latest.osm pc_gtfs -o pc_gtfs_pfaedle

      - name: Zip PC results
        run: zip -r pc_gtfs_pfaedle.zip pc_gtfs_pfaedle

      - name: Upload PC results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: pc_gtfs_pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: pc_gtfs_pfaedle.zip      # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Unzip Metrolink GTFS
        run: |
          mkdir metrolink-gtfs  
          unzip metrolink.zip -d metrolink-gtfs  

      - name: Unzip of ile de france gtfs
        run: |
          mkdir IDFM-gtfs
          unzip IDFM-gtfs.zip -d IDFM-gtfs

      - name: Unzip of HK gtfs
        run: |
          mkdir hk_gtfs
          unzip hk_gtfs.zip -d hk_gtfs

      - name: Run Metrolink pfaedle
        run: |
          ./pfaedle/build/pfaedle -x railonly-socal-latest.osm metrolink-gtfs

      - name: Zip metrolink file
        run: zip -r metrolink-pfaedle.zip gtfs-out

      - name: Remove old folder
        run: rm -rf gtfs-out

      - name: Run Ile de france pfaedle
        run: |
          ./pfaedle/build/pfaedle -x ile-de-france-latest.osm IDFM-gtfs

      - name: Zip the resulting GTFS Ile de France
        run: zip -r IDFM-gtfs-pfaedle.zip gtfs-out

      - name: Remove old folder
        run: rm -rf gtfs-out

      - name: Run Hong Kong pfaedle
        run: |
          ./pfaedle/build/pfaedle -x guangdong-latest.osm hk_gtfs

      - name: Zip the resulting GTFS Hong Kong
        run: zip -r hk-gtfs-pfaedle.zip gtfs-out

      - name: Upload Metrolink Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: metrolink-pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: metrolink-pfaedle.zip     # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Upload Asset Ile De France
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: IDFM-gtfs-pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: IDFM-gtfs-pfaedle.zip      # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Upload Asset Hong Kong
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: hk-gtfs-pfaedle.zip # Replace with the actual path to your file
          ASSET_NAME: hk-gtfs-pfaedle.zip      # Replace with the desired name of the asset
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''
