name: Update Pfaedle files

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download unzip and zip
        run: sudo apt install unzip zip

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: install cmake and gcc
        run: sudo apt install cmake gcc

      - name: Build Pfaedle
        run: |
          git clone --recurse-submodules https://github.com/ad-freiburg/pfaedle
          cd pfaedle
          mkdir build && cd build
          cmake ..
          make -j
          sudo make install
          cd ..

      - name: Current dir
        run: |
          echo "current dir"
          echo $(pwd)
          echo "ls"
          ls

      - name: Download osm files
        run: |
          wget https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf
          wget https://download.geofabrik.de/europe/portugal-latest.osm.pbf
          wget https://github.com/catenarytransit/osm-filter/releases/download/latest/railonly-europe-latest.osm.pbf

      - name: Filter Portugal
        run: |
          osmium tags-filter -o railonly-portugal-latest.osm.pbf --expressions=railway-filter.txt portugal-latest.osm.pbf

      - name: Convert OSM files
        run: |
          osmconvert ile-de-france-latest.osm.pbf -o=ile-de-france-latest.osm
          osmconvert railonly-portugal-latest.osm.pbf -o=railonly-portugal-latest.osm
          osmconvert railonly-europe-latest.osm.pbf -o=railonly-europe-latest.osm

      - name: Download zip of ile de france gtfs
        uses: wei/wget@v1
        with:
          args: https://eu.ftp.opendatasoft.com/stif/GTFS/IDFM-gtfs.zip

      - name: Download Eurostar GTFS
        uses: wei/wget@v1
        with:
          args: https://gtfs.eurostar.com/assets/gtfs.zip -O eurostar.zip

      - name: Download SNCB GTFS
        run: wget https://sncb-opendata.hafas.de/gtfs/static/c21ac6758dd25af84cca5b707f3cb3de -O sncb_gtfs.zip 

      - name: Download PC GTFS
        run: wget https://publico.cp.pt/gtfs/gtfs.zip -O pc_gtfs.zip

      - name: Download Renfe Operadora
        run: wget https://ssl.renfe.com/gtransit/Fichero_AV_LD/google_transit.zip -O renfe_operadora.zip

      - name: Unzip PC GTFS
        run: unzip pc_gtfs.zip -d pc_gtfs

      - name: Unzip SNCB GTFS
        run: unzip sncb_gtfs.zip -d sncb_gtfs

      - name: Unzip Eurostar GTFS
        run: unzip eurostar.zip -d eurostar

      - name: Unzip renfe operadora
        run: unzip renfe_operadora.zip -d renfe_operadora 

      - name: Run pfaedle Portugal
        run: ./pfaedle/build/pfaedle -x railonly-portugal-latest.osm pc_gtfs -F --inplace --write-colors

      - name: Zip PC results
        run: zip -9 -r pc_gtfs_pfaedle.zip pc_gtfs/*

      - name: Upload PC results
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: pc_gtfs_pfaedle.zip # Replace with the actual path to your file
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != ''
      
      - name: Run pfaedle SNCB
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm sncb_gtfs -F --inplace  --write-colors --drop-shapes true

      - name: Zip SNCF pfaedle result
        run: zip -9 -r sncb_gtfs_pfaedle.zip sncb_gtfs/*

      - name: Upload SNCB result
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: sncb_gtfs_pfaedle.zip # Replace with the actual path to your file
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' 

      - name: Run pfaedle renfe operadora
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm renfe_operadora -F --inplace --write-colors

      - name: Zip renfe operadora results
        run: zip -9 -r renfe_operadora_pfaedle.zip renfe_operadora/*

      - name: Upload Renfe Operadora
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: renfe_operadora_pfaedle.zip # Replace with the actual path to your file
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != ''     

      - name: Unzip of ile de france gtfs
        run: |
          mkdir IDFM-gtfs
          unzip IDFM-gtfs.zip -d IDFM-gtfs
        
      - name: Run Ile de france pfaedle Local rail and bus
        run: |
          ./pfaedle/build/pfaedle -x ile-de-france-latest.osm IDFM-gtfs -F --inplace --mots metro,streetcar,tram,subway,coach,monorail,trolley,trolleybus,bus

      - name: Run Ile de france pfaedle Intercity rail
        run: |
          ./pfaedle/build/pfaedle -x railonly-europe-latest.osm IDFM-gtfs -F --inplace --mots rail

      - name: Zip the resulting GTFS Ile de France
        run: zip -9 -r IDFM-gtfs-pfaedle.zip IDFM-gtfs/*

      - name: Upload Asset Ile De France
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: IDFM-gtfs-pfaedle.zip # Replace with the actual path to your file
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != ''

      - name: wget Trenord
        uses: wei/wget@v1
        with:
          args: https://www.dati.lombardia.it/download/3z4k-mxz9/application%2Fzip -O trenord.zip

      - name: Unzip Trenord
        run: unzip trenord.zip -d trenord

      - name: Pfaedle trenord
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm trenord -F --inplace --mots rail

      - name: Zip trenord
        run: zip -9 -r trenord-pfaedle.zip trenord/*

      - name: Upload Asset trenord
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: trenord-pfaedle.zip # Replace with the actual path to your file
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != ''

      - name: Download Zssk GTFS
        uses: wei/wget@v1
        with:
          args: https://www.zsr.sk/files/pre-cestujucich/cestovny-poriadok/gtfs/gtfs.zip -O zssk_gtfs.zip

      - name: Unzip ZSSK
        run: unzip zssk_gtfs.zip -d zssk_gtfs

      - name: Pfaedle ZSSK
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm zssk_gtfs -F --inplace --mots rail --drop-shapes true

      - name: Zip ZSSK
        run: zip -9 -r zssk_gtfs-pfaedle.zip zssk_gtfs/*

      - name: Upload Asset ZSSK
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: zssk_gtfs-pfaedle.zip # Replace with the actual path to your file
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != ''

      - name: Name download Flix EU
        uses: wei/wget@v1
        with:
          args: http://gtfs.gis.flix.tech/gtfs_generic_eu.zip

      - name: Unzip EU Flix
        run: unzip gtfs_generic_eu.zip -d flix_eu

      - name: pfaedle Flix EU
        run: ./pfaedle/build/pfaedle -x railonly-europe-latest.osm flix_eu -F --inplace --mots rail --drop-shapes true

      - name: Zip Flix EU
        run: zip -9 -r flix_eu-pfaedle.zip flix_eu/*

      - name: Upload Asset Flix
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: flix_eu-pfaedle.zip # Replace with the actual path to your file
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != ''
